<?php

/**
 * Implements hook_menu().
 */
function quicklink_menu() {
  $items['admin/config/development/performance/default'] = array(
    'title' => 'Performance',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file path' => backdrop_get_path('module', 'system'),
    'weight' => -10,
  );
  $items['admin/config/development/performance/quicklink'] = array(
    'title' => 'Quicklink',
    'description' => 'Pass configuration to the Quicklink library to prefetch links.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('quicklink_settings'),
    'access arguments' => array('administer quicklink'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'quicklink.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function quicklink_permission() {
  return array(
    'administer quicklink' => array(
      'title' => t('Administer Quicklink'),
      'description' => t('Configure quicklink settings.'),
    ),
  );
}

/**
 * Implements hook_config_info().
 */
function quicklink_config_info() {
  $prefixes['quicklink.settings'] = array(
    'label' => t('Quicklink settings'),
    'group' => t('Performance'),
  );

  return $prefixes;
}

/**
 * Implements hook_library_info().
 */
function quicklink_library_info() {
  $libraries = array();

  $libraries['quicklink'] = array(
    'title' => 'Quicklink',
    'version' => '1.0.0',
    'js' => array(
      'https://unpkg.com/quicklink@1.0.0/dist/quicklink.umd.js' => array(
        'minified' => TRUE,
        'type' => 'external',
        'weight' => -20
      ),
    ),
  );

  $libraries['quicklink_init'] = array(
    'title' => 'Quicklink init',
    'version' => '1.0.0',
    'js' => array(
      backdrop_get_path('module', 'quicklink') . '/js/quicklink_init.js' => array('weight' => -10),
    ),
    'css' => array(
      backdrop_get_path('module', 'quicklink') . '/css/quicklink-debug.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );

  $libraries['quicklink_polyfill'] = array(
    'title' => 'Polyfill',
    'version' => '2',
    'js' => array(
      'https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver%2CIntersectionObserverEntry%2CURL%2CObject.assign%2CArray.from%2CArray.prototype.includes%2CString.prototype.includes%2CElement.prototype.matches%2CPromise%2CPromise.prototype.finally' => array(
        'minified' => TRUE,
        'type' => 'external',
        'weight' => -100
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_requirements().
 */
function quicklink_requirements($phase) {
  $debug_mode = config_get('quicklink.settings', 'enable_debug_mode');
  $requirements = array();
  if ($debug_mode) {
    $requirements['quicklink'] = array(
      'title' => t('Quicklink debug mode'),
      'value' => t('Enabled'),
      'severity' => REQUIREMENT_WARNING,
      'description' => t('When enabled, Quicklink development information is logged to the JavaScript console and shown on the screen. This should be <a href="@url">disabled</a> on public sites.', array('@url' => url('admin/config/development/performance/quicklink', array('fragment' => 'edit-debug')))),
    );
  }
  return $requirements;
}

/**
 * Implements hook_preprocess_layout().
 *
 * Insert JavaScript to the appropriate scope/region of the page.
 */
function quicklink_preprocess_layout(&$variables) {
  // Load current configuration.
  $config = config('quicklink.settings');
  $settings = array();
  $selector = $config->get('selector');

  // Get debug variable.
  $debug = $config->get('enable_debug_mode');
  $debug_log = array();

  // Load the library unless we disable later.
  $load_library = TRUE;

  // Always ignore the logout link.
  $url_patterns_to_ignore = array('user/logout');
  $debug_log[] = 'Quicklink will ignore "user/logout" URL pattern.';

  $allowed_domains = array();

  // Populate and remove line returns from URL patterns to ignore.
  foreach (explode(PHP_EOL, $config->get('url_patterns_to_ignore')) as $value) {
    $pattern = str_replace("\r", '', $value);

    if (!empty($pattern)) {
      $url_patterns_to_ignore[] = $pattern;
    }
  }

  // Populate and remove line returns from allowed domains.
  foreach (explode(PHP_EOL, $config->get('allowed_domains')) as $value) {
    $domain = str_replace("\r", '', $value);

    if (!empty($domain)) {
      $allowed_domains[] = $domain;
    }
  }

  // Populate and remove line returns from "Prefetch these paths only".
  foreach (explode(PHP_EOL, $config->get('prefetch_only_paths')) as $value) {
    $path = str_replace("\r", '', $value);

    if (!empty($path)) {
      $prefetch_only_paths[] = $path;
    }
  }

  // Check for "Ignore Hashes" option.
  if ($config->get('ignore_hashes') == 1) {
    $url_patterns_to_ignore[] = '#';
    $debug_log[] = 'Quicklink will ignore URLs with hashes(#).';
  }

  // If "Ignore admin paths" is selected, ignore the admin paths.
  if ($config->get('ignore_admin_paths') == 1) {
    $url_patterns_to_ignore[] = '/admin';
    $url_patterns_to_ignore[] = '/edit';

    // If elements match these selector pattern, they will not be prefetched.
    $admin_link_container_patterns = array('#admin-bar a', '.contextual-links-wrapper a', '#tabs a', '#navbar-administration');

    $settings['admin_link_container_patterns'] = $admin_link_container_patterns;
    $debug_log[] = 'Quicklink will ignore admin URL patterns.';
  }

  $node = menu_get_object();
  if ($node instanceof Node) {
    $no_load_content_types = $config->get('no_load_content_types');

    if (in_array($node->type, $no_load_content_types) && $no_load_content_types[$node->type]) {
      $load_library = FALSE;
      $debug_log[] = 'Library not loaded because content type "' . $node->type . '" is specified to not load library.';
    }
  }

  // If user is logged in AND "Prefetch for anonymous users only" is selected,
  // do not load library.
  global $user;

  if (isset($user) && $config->get('no_load_when_authenticated') == 1 && !empty($user->uid) && $user->uid >= 1) {
    $load_library = FALSE;
    $debug_log[] = 'Library not loaded because user is authenticated.';
  }

  // Disable the library when a session is started.
  if ($config->get('no_load_when_session')) {
    $session = backdrop_session_started();

    if (!empty($session)) {
      $load_library = FALSE;
      $debug_log[] = 'Library not loaded because PHP session is started.';
    }
  }

  // Disable the library if page caching is disabled.
  if ($config->get('no_load_without_page_cache') && config_get('system.core', 'cache') == FALSE) {
    $load_library = FALSE;
    $debug_log[] = 'Library not loaded because Backdrop page caching is disabled.';
  }

  backdrop_add_library('quicklink', 'quicklink_init');
  $settings['ignore_admin_paths'] = $config->get('ignore_admin_paths');
  $settings['ignore_ajax_links'] = $config->get('ignore_ajax_links');
  $settings['ignore_file_ext'] = $config->get('ignore_file_ext');
  $settings['debug'] = $debug;

  if (!empty($url_patterns_to_ignore[0])) {
    $settings['url_patterns_to_ignore'] = $url_patterns_to_ignore;
    $debug_log['url_patterns_to_ignore'][] = $url_patterns_to_ignore;
  }

  if (!empty($selector)) {
    $settings['selector'] = $selector;
    $debug_log[] = 'Selector for Quicklink to parse: ' . $selector;
  }

  if (!empty($allowed_domains[0])) {
    $settings['allowed_domains'] = $allowed_domains;
    $debug_log['allowed_domains'][] = $allowed_domains;
  }

  if (!empty($prefetch_only_paths[0])) {
    $settings['prefetch_only_paths'] = $prefetch_only_paths;
    $debug_log['prefetch_only_paths'][] = $prefetch_only_paths;
  }

  if ($load_library) {
    if ($config->get('load_polyfill') == 1) {
      backdrop_add_library('quicklink', 'quicklink_polyfill');
      $debug_log[] = 'Intersection Observer polyfill library loaded';
    }

    backdrop_add_library('quicklink', 'quicklink');
  }

  if ($debug) {
    $settings['debug'] = 1;
    backdrop_add_library('quicklink', 'quicklink_debug');
    $settings['debug_log'] = $debug_log;
  }
  backdrop_add_js(array('quicklink' => $settings), 'setting');
  backdrop_add_js(backdrop_get_path('module', 'quicklink') . '/js/quicklink_init.js');
}
